/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: db46c0a338f7b13977b99c03f7a7f617)
interface __BaseEnv_Env {
	REACTION_CONFIG: string;
	SLACK_BOT_TOKEN: string;
	SLACK_SIGNING_SECRET: string;
	TYPESAFE_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "REACTION_CONFIG" | "SLACK_BOT_TOKEN" | "SLACK_SIGNING_SECRET" | "TYPESAFE_API_KEY">> {}
}
